// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: api/proto/transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на анализ транзакции
type AnalyzeTransactionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TransactionId       string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountNumber       string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Amount              float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency            string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	TransactionType     string                 `protobuf:"bytes,5,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	CounterpartyAccount string                 `protobuf:"bytes,6,opt,name=counterparty_account,json=counterpartyAccount,proto3" json:"counterparty_account,omitempty"`
	CounterpartyBank    string                 `protobuf:"bytes,7,opt,name=counterparty_bank,json=counterpartyBank,proto3" json:"counterparty_bank,omitempty"`
	CounterpartyCountry string                 `protobuf:"bytes,8,opt,name=counterparty_country,json=counterpartyCountry,proto3" json:"counterparty_country,omitempty"`
	Channel             string                 `protobuf:"bytes,9,opt,name=channel,proto3" json:"channel,omitempty"`
	UserId              string                 `protobuf:"bytes,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BranchId            string                 `protobuf:"bytes,11,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Timestamp           string                 `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AnalyzeTransactionRequest) Reset() {
	*x = AnalyzeTransactionRequest{}
	mi := &file_api_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTransactionRequest) ProtoMessage() {}

func (x *AnalyzeTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTransactionRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *AnalyzeTransactionRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AnalyzeTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AnalyzeTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AnalyzeTransactionRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *AnalyzeTransactionRequest) GetCounterpartyAccount() string {
	if x != nil {
		return x.CounterpartyAccount
	}
	return ""
}

func (x *AnalyzeTransactionRequest) GetCounterpartyBank() string {
	if x != nil {
		return x.CounterpartyBank
	}
	return ""
}

func (x *AnalyzeTransactionRequest) GetCounterpartyCountry() string {
	if x != nil {
		return x.CounterpartyCountry
	}
	return ""
}

func (x *AnalyzeTransactionRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *AnalyzeTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnalyzeTransactionRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *AnalyzeTransactionRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Ответ на анализ транзакции
type AnalyzeTransactionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessingId   string                 `protobuf:"bytes,1,opt,name=processing_id,json=processingId,proto3" json:"processing_id,omitempty"`
	RiskScore      int32                  `protobuf:"varint,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	RiskLevel      string                 `protobuf:"bytes,3,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	Flags          []string               `protobuf:"bytes,4,rep,name=flags,proto3" json:"flags,omitempty"`
	Recommendation string                 `protobuf:"bytes,5,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	AnalyzedAt     string                 `protobuf:"bytes,6,opt,name=analyzed_at,json=analyzedAt,proto3" json:"analyzed_at,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeTransactionResponse) Reset() {
	*x = AnalyzeTransactionResponse{}
	mi := &file_api_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTransactionResponse) ProtoMessage() {}

func (x *AnalyzeTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTransactionResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeTransactionResponse) GetProcessingId() string {
	if x != nil {
		return x.ProcessingId
	}
	return ""
}

func (x *AnalyzeTransactionResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AnalyzeTransactionResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *AnalyzeTransactionResponse) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *AnalyzeTransactionResponse) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *AnalyzeTransactionResponse) GetAnalyzedAt() string {
	if x != nil {
		return x.AnalyzedAt
	}
	return ""
}

func (x *AnalyzeTransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Запрос на получение статуса транзакции
type GetTransactionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessingId  string                 `protobuf:"bytes,1,opt,name=processing_id,json=processingId,proto3" json:"processing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionStatusRequest) Reset() {
	*x = GetTransactionStatusRequest{}
	mi := &file_api_proto_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionStatusRequest) ProtoMessage() {}

func (x *GetTransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionStatusRequest) GetProcessingId() string {
	if x != nil {
		return x.ProcessingId
	}
	return ""
}

// Ответ со статусом транзакции
type GetTransactionStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProcessingId      string                 `protobuf:"bytes,1,opt,name=processing_id,json=processingId,proto3" json:"processing_id,omitempty"`
	TransactionId     string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	RiskScore         int32                  `protobuf:"varint,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	RiskLevel         string                 `protobuf:"bytes,5,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	Flags             []string               `protobuf:"bytes,6,rep,name=flags,proto3" json:"flags,omitempty"`
	AnalysisTimestamp string                 `protobuf:"bytes,7,opt,name=analysis_timestamp,json=analysisTimestamp,proto3" json:"analysis_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTransactionStatusResponse) Reset() {
	*x = GetTransactionStatusResponse{}
	mi := &file_api_proto_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionStatusResponse) ProtoMessage() {}

func (x *GetTransactionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionStatusResponse) GetProcessingId() string {
	if x != nil {
		return x.ProcessingId
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *GetTransactionStatusResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *GetTransactionStatusResponse) GetAnalysisTimestamp() string {
	if x != nil {
		return x.AnalysisTimestamp
	}
	return ""
}

// Запрос на генерацию случайной транзакции
type GenerateRandomTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRandomTransactionRequest) Reset() {
	*x = GenerateRandomTransactionRequest{}
	mi := &file_api_proto_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRandomTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRandomTransactionRequest) ProtoMessage() {}

func (x *GenerateRandomTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRandomTransactionRequest.ProtoReflect.Descriptor instead.
func (*GenerateRandomTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_transaction_proto_rawDescGZIP(), []int{4}
}

// Ответ с сгенерированной транзакцией
type GenerateRandomTransactionResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TransactionId       string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountNumber       string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Amount              float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency            string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	TransactionType     string                 `protobuf:"bytes,5,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	CounterpartyAccount string                 `protobuf:"bytes,6,opt,name=counterparty_account,json=counterpartyAccount,proto3" json:"counterparty_account,omitempty"`
	CounterpartyBank    string                 `protobuf:"bytes,7,opt,name=counterparty_bank,json=counterpartyBank,proto3" json:"counterparty_bank,omitempty"`
	CounterpartyCountry string                 `protobuf:"bytes,8,opt,name=counterparty_country,json=counterpartyCountry,proto3" json:"counterparty_country,omitempty"`
	Channel             string                 `protobuf:"bytes,9,opt,name=channel,proto3" json:"channel,omitempty"`
	UserId              string                 `protobuf:"bytes,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BranchId            string                 `protobuf:"bytes,11,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GenerateRandomTransactionResponse) Reset() {
	*x = GenerateRandomTransactionResponse{}
	mi := &file_api_proto_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRandomTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRandomTransactionResponse) ProtoMessage() {}

func (x *GenerateRandomTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRandomTransactionResponse.ProtoReflect.Descriptor instead.
func (*GenerateRandomTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateRandomTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GenerateRandomTransactionResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *GenerateRandomTransactionResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GenerateRandomTransactionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GenerateRandomTransactionResponse) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *GenerateRandomTransactionResponse) GetCounterpartyAccount() string {
	if x != nil {
		return x.CounterpartyAccount
	}
	return ""
}

func (x *GenerateRandomTransactionResponse) GetCounterpartyBank() string {
	if x != nil {
		return x.CounterpartyBank
	}
	return ""
}

func (x *GenerateRandomTransactionResponse) GetCounterpartyCountry() string {
	if x != nil {
		return x.CounterpartyCountry
	}
	return ""
}

func (x *GenerateRandomTransactionResponse) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *GenerateRandomTransactionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateRandomTransactionResponse) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

var File_api_proto_transaction_proto protoreflect.FileDescriptor

const file_api_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/transaction.proto\x12\vtransaction\"\xc9\x03\n" +
	"\x19AnalyzeTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12)\n" +
	"\x10transaction_type\x18\x05 \x01(\tR\x0ftransactionType\x121\n" +
	"\x14counterparty_account\x18\x06 \x01(\tR\x13counterpartyAccount\x12+\n" +
	"\x11counterparty_bank\x18\a \x01(\tR\x10counterpartyBank\x121\n" +
	"\x14counterparty_country\x18\b \x01(\tR\x13counterpartyCountry\x12\x18\n" +
	"\achannel\x18\t \x01(\tR\achannel\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\tR\x06userId\x12\x1b\n" +
	"\tbranch_id\x18\v \x01(\tR\bbranchId\x12\x1c\n" +
	"\ttimestamp\x18\f \x01(\tR\ttimestamp\"\xf6\x01\n" +
	"\x1aAnalyzeTransactionResponse\x12#\n" +
	"\rprocessing_id\x18\x01 \x01(\tR\fprocessingId\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x05R\triskScore\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x03 \x01(\tR\triskLevel\x12\x14\n" +
	"\x05flags\x18\x04 \x03(\tR\x05flags\x12&\n" +
	"\x0erecommendation\x18\x05 \x01(\tR\x0erecommendation\x12\x1f\n" +
	"\vanalyzed_at\x18\x06 \x01(\tR\n" +
	"analyzedAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"B\n" +
	"\x1bGetTransactionStatusRequest\x12#\n" +
	"\rprocessing_id\x18\x01 \x01(\tR\fprocessingId\"\x85\x02\n" +
	"\x1cGetTransactionStatusResponse\x12#\n" +
	"\rprocessing_id\x18\x01 \x01(\tR\fprocessingId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x05R\triskScore\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x05 \x01(\tR\triskLevel\x12\x14\n" +
	"\x05flags\x18\x06 \x03(\tR\x05flags\x12-\n" +
	"\x12analysis_timestamp\x18\a \x01(\tR\x11analysisTimestamp\"\"\n" +
	" GenerateRandomTransactionRequest\"\xb3\x03\n" +
	"!GenerateRandomTransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12)\n" +
	"\x10transaction_type\x18\x05 \x01(\tR\x0ftransactionType\x121\n" +
	"\x14counterparty_account\x18\x06 \x01(\tR\x13counterpartyAccount\x12+\n" +
	"\x11counterparty_bank\x18\a \x01(\tR\x10counterpartyBank\x121\n" +
	"\x14counterparty_country\x18\b \x01(\tR\x13counterpartyCountry\x12\x18\n" +
	"\achannel\x18\t \x01(\tR\achannel\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\tR\x06userId\x12\x1b\n" +
	"\tbranch_id\x18\v \x01(\tR\bbranchId2\xe4\x02\n" +
	"\x12TransactionService\x12e\n" +
	"\x12AnalyzeTransaction\x12&.transaction.AnalyzeTransactionRequest\x1a'.transaction.AnalyzeTransactionResponse\x12k\n" +
	"\x14GetTransactionStatus\x12(.transaction.GetTransactionStatusRequest\x1a).transaction.GetTransactionStatusResponse\x12z\n" +
	"\x19GenerateRandomTransaction\x12-.transaction.GenerateRandomTransactionRequest\x1a..transaction.GenerateRandomTransactionResponseB'Z%bank-aml-system/api/proto;transactionb\x06proto3"

var (
	file_api_proto_transaction_proto_rawDescOnce sync.Once
	file_api_proto_transaction_proto_rawDescData []byte
)

func file_api_proto_transaction_proto_rawDescGZIP() []byte {
	file_api_proto_transaction_proto_rawDescOnce.Do(func() {
		file_api_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_transaction_proto_rawDesc), len(file_api_proto_transaction_proto_rawDesc)))
	})
	return file_api_proto_transaction_proto_rawDescData
}

var file_api_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_transaction_proto_goTypes = []any{
	(*AnalyzeTransactionRequest)(nil),         // 0: transaction.AnalyzeTransactionRequest
	(*AnalyzeTransactionResponse)(nil),        // 1: transaction.AnalyzeTransactionResponse
	(*GetTransactionStatusRequest)(nil),       // 2: transaction.GetTransactionStatusRequest
	(*GetTransactionStatusResponse)(nil),      // 3: transaction.GetTransactionStatusResponse
	(*GenerateRandomTransactionRequest)(nil),  // 4: transaction.GenerateRandomTransactionRequest
	(*GenerateRandomTransactionResponse)(nil), // 5: transaction.GenerateRandomTransactionResponse
}
var file_api_proto_transaction_proto_depIdxs = []int32{
	0, // 0: transaction.TransactionService.AnalyzeTransaction:input_type -> transaction.AnalyzeTransactionRequest
	2, // 1: transaction.TransactionService.GetTransactionStatus:input_type -> transaction.GetTransactionStatusRequest
	4, // 2: transaction.TransactionService.GenerateRandomTransaction:input_type -> transaction.GenerateRandomTransactionRequest
	1, // 3: transaction.TransactionService.AnalyzeTransaction:output_type -> transaction.AnalyzeTransactionResponse
	3, // 4: transaction.TransactionService.GetTransactionStatus:output_type -> transaction.GetTransactionStatusResponse
	5, // 5: transaction.TransactionService.GenerateRandomTransaction:output_type -> transaction.GenerateRandomTransactionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_transaction_proto_init() }
func file_api_proto_transaction_proto_init() {
	if File_api_proto_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_transaction_proto_rawDesc), len(file_api_proto_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_transaction_proto_goTypes,
		DependencyIndexes: file_api_proto_transaction_proto_depIdxs,
		MessageInfos:      file_api_proto_transaction_proto_msgTypes,
	}.Build()
	File_api_proto_transaction_proto = out.File
	file_api_proto_transaction_proto_goTypes = nil
	file_api_proto_transaction_proto_depIdxs = nil
}
